import './globals.css'
import Image from 'next/image';

import Header from './components/header'
import '@fontsource/poppins/400.css';
import '@fontsource/poppins/500.css';
import '@fontsource/poppins/600.css';
import '@fontsource/poppins/700.css';
import '@fontsource/poppins/800.css';
import '@fontsource/poppins/900.css';
import Footer from './components/footer';
import Footer2 from './components/footer2';

export const metadata = {
  title: 'Apartment Hunt | Best place for finding apartment for rent',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className='font-poppins'>
      <Header/>
      
      {children}

      </body>
    </html>
  )
}
